### PR TITLE
CSS and stuff

### PR DESCRIPTION
**Pull request by Zth--**
WIP, we can discuss here

wip

### CODE REVIEW

**Comment by gbasood** [comment]
\>rounding
pls no

**Comment by Zth--** [comment]
a small (very small) rounding is much much more better than shitty squares

**Comment by Efruit** [comment]
> small (very small) rounding

not one border-radius in the screenshotf is small
let alone very small

**Comment by Zth--** [comment]
even the chat we're using in this page has roundings.

http://i.imgur.com/2KVMIrm.png what about this? I don't like the buttons, but the front itself looks better than squares

**Comment by gbasood** [comment]
since the new style from @Efruit is so robust i'm gonna close this

**Pull request closed without merging**
